### ISSUE TITLE
Need help to get VersionPress run on Google Cloud

### ISSUE THREAD

**Issue by andreaskviby** [versionpress/support#23]
Hey
We have over 50 Wordpress sites that we are moving to Google Cloud hosting but we want VersionPress for development and easy to manage all the sites. Can someone at VersionPress help me?

**Comment by borekb** [comment]
Hi, what do you need help with? Please try to be as specific as possible (e.g., "Google Cloud" is a generic brand under which there are many specific services). Thanks.

**Comment by andreaskviby** [comment]
Hey
We have setup a test site members.fooever.com and if you want you can login and check that to see if it will be possible to use VersionPress on that. All sites will be setup similar and the goal is that all sites will be synced through git down to all our developers and when they push the site will be updated automated. This is the dream solution for us, we are 17 developers in Sweden and run a lot of sites.

Its setup as an VM Instance on Google.


Best regards

Andreas Kviby

**Comment by borekb** [comment]
If it's a VM you can certainly make VersionPress run – all the requirements are described here: http://docs.versionpress.net/en/getting-started/installation-uninstallation

Sync between environments is something that VersionPress supports since 2.0, see e.g. [this blog post](http://blog.versionpress.net/2015/09/versionpress-2-0-staging/), but major usability improvements are coming in v3 which will be out in a couple of weeks.

If you're evaluating whether VersionPress will be good for your scenario, please go through http://docs.versionpress.net/en. Just to be clear, VersionPress is currently in the Early Access Program mode which is described here: http://docs.versionpress.net/en/getting-started/about-eap.

**Comment by andreaskviby** [comment]
Hey
Okey but I get this screen, how can I solve that? I am not a hosting pro and I am willing to pay to make this work.

/Andreas Kviby

**Comment by borekb** [comment]
There's no attachment here.

**Comment by borekb** [comment]
Closing this for now. If you need further assistance @andreaskviby please reopen it.
