### ISSUE TITLE
Tracking Visual Composer

### ISSUE THREAD

**Issue by HammyHavoc** [versionpress/support#26]
VC uses custom database tables (to my knowledge), and as it's increasingly popular with themes and clients, it seems like a good choice to start tracking it.

**Comment by pavelevap** [comment]
@HammyHavoc: Thank you for suggestion! We are planning to support plugins and themes in the future (probably our main task for VersionPress 4.0). I did not find any custom database tables, but Visual Composer is currently not supported because of many custom shortcodes which are referenced to IDs and not tracked by VersionPress yet.

Similar issue: #24

**Comment by borekb** [comment]
Exactly as @pavelevap said. Thank you for your feedback, @HammyHavoc, we're looking forward to that support too :) I'm closing this issue for now.

**Comment by NirBehalf** [comment]
@borekb Hey - Is there any update within? We are using Visual Composer plugin and we are still facing issues while merging our code with VC images and custom CSS shortcodes.
