### ISSUE TITLE
parse error when trying to clone site

### ISSUE THREAD

**Issue by chazragg** [versionpress/support#97]
so i would like to implement versionpress onto my current website but i seem to be running in an issue

the command i am using is wp vp clone --name=test --require=wp-content/plugins/versionpress/src/Cli/vp.php

(reason i use --require is because 1and1 runs php 5.5 and it is required :P)

when i run the command it says there is a parse error: syntax error, unexpected '.', expecting '&' or variable (t_variable) in GitRepositor.php on line 491

i don't know much about the git files and didn't want to go root round an changing stuff.

if you require any more information feel free to ask and i will provide.

**Comment by borekb** [comment]
This is most likely because of the old PHP version. VersionPress requires 5.6+, see [system requirements](https://docs.versionpress.net/en/getting-started/installation-uninstallation).

**Comment by chazragg** [comment]
i should have maybe said this before, i did get it to clone the site but i had some SQL issues i needed to sort out but now it is just giving me this error when it use to work.

**Comment by borekb** [comment]
What does `php -v` print?

**Comment by chazragg** [comment]
php 4.4.9 (cgi-fcgi) (built: Feb 28 2017 11:31:58)
copyright (c) 1997-2008 The PHP Group
Zend Engine v1.3.0, Ccopyright (c) 1998-2004 Zend Technologies


i find this weird as through 1 and 1 i have set it to use php 7 for my wordpress.

**Comment by pavelevap** [comment]
@chazragg: Yes, it will be definitely old PHP version, please see this issue: https://github.com/versionpress/versionpress/issues/1077

VP "mostly" works, because part of VP (in WP admin) is based on your selected PHP 7 version, but when you try to do something with WP-CLI (for example cloning), you will end up with error when there is older PHP version internally used on shared server. You should contact your webhoster to upgrade PHP version for WP-CLI.

**Comment by chazragg** [comment]
ok, thanks for the help
