### ISSUE TITLE
Error: Failed creating database. 

### ISSUE THREAD

**Issue by mvedma** [versionpress/support#99]
Please be specific when describing the issue. Also, these details will help:

- VersionPress version: '4.0-beta
- WordPress version:'4.7.5'
- OS, webserver, PHP:Windows 7 Professional Edition Service Pack 1),xampp,5.6.30
- Git version:2.9.0

You can get more details from your system info page: <http://docs.versionpress.net/en/troubleshooting/system-info-page>

**Comment by mvedma** [comment]
Hello,
I get the following error when I try to create a clone, it is unable to create a database for the cloned website, may you please help me understand what is causing this.

![image](https://user-images.githubusercontent.com/12765295/28230268-35a35670-68b4-11e7-91a0-19d3eb7531f2.png)

**Comment by borekb** [comment]
@pavelevap any ideas?

**Comment by pavelevap** [comment]
Ah, sorry, I missed this issue somehow :-(

PHP Notice is related to [this line](https://github.com/phpmyadmin/sql-parser/blob/v3.4.0/src/Components/OptionsArray.php#L218), but nothing suspicious here and I am not sure where could be sql-parser used before "Site files cloned" [message](https://github.com/versionpress/versionpress/blob/73ff46674828218c271bbcaf820c50ff4cdf8cd4/plugins/versionpress/src/Cli/vp.php#L498).

Error related to creating database is [here](https://github.com/versionpress/versionpress/blob/73ff46674828218c271bbcaf820c50ff4cdf8cd4/plugins/versionpress/src/Cli/vp.php#L344), but creating database should be basic WP-CLI command.

@mvedma: Hi, could you please try to create database directly with WP-CLI command `wp db create` ([docs](https://developer.wordpress.org/cli/commands/db/create/)) to confirm it works well?

What is your WP-CLI version? There was also similar [problem](https://github.com/wp-cli/wp-cli/issues/4120) related to Windows and xampp and it should be fixed in version 1.2.1.

**Comment by zauker** [comment]
I had a similar issue.
Performing clone command I received the message:

Error: Failed creating database. Details:
env: mysql: No such file or directory

In my case I solved setting the correct $PATH of XAMPP binaries.
To use the command i use a shell with daemon user (the user used for XAMPP on Mac) and this user don't have in PATH the folder of XAMP binaries

performing the command
export PATH=$PATH:/Applications/XAMPP/bin/

after that the clone command works fine

**Comment by pavelevap** [comment]
Thank you, @zauker!

I am closing this issue for now, because it is probably related to configuration problems. Anybody can comment or reopen if there is any additional info.
